# Generated by Django 5.0 on 2023-12-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='askmodel',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
