# Generated by Django 5.0 on 2024-02-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_askcategorymodel_askmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='askmodel',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
