# Generated by Django 5.0 on 2024-02-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_askmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='askmodel',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
