# Generated by Django 5.0 on 2024-02-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0010_adminaskratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaskratingmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
