# Generated by Django 5.0 on 2023-12-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='thumb',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
