# Generated by Django 5.0 on 2023-12-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmodel_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='slug',
            field=models.TextField(default='slug'),
        ),
    ]
