# Generated by Django 5.0 on 2024-04-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogmodel_crypto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='crypto_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
