# Generated by Django 5.0 on 2024-04-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feedcategorymodel_alter_feedcommentmodel_feed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmodel',
            name='hashtags',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
